// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJdTq7QivUrFXgu6Jp6UeKQqy4D4Q6EAQ',
    appId: '1:640794025510:web:4c4b0f8be4be79255190e7',
    messagingSenderId: '640794025510',
    projectId: 'leo-anime-auth',
    authDomain: 'leo-anime-auth.firebaseapp.com',
    storageBucket: 'leo-anime-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANlx02I8sOI3s8E5Hg6UY04Vm-2QaLqeQ',
    appId: '1:640794025510:android:0b7531e6f8d963265190e7',
    messagingSenderId: '640794025510',
    projectId: 'leo-anime-auth',
    storageBucket: 'leo-anime-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCas0a9mEHAQok97n-mGC3uY6ysQqESHRs',
    appId: '1:640794025510:ios:b0cb88d99e23efd05190e7',
    messagingSenderId: '640794025510',
    projectId: 'leo-anime-auth',
    storageBucket: 'leo-anime-auth.appspot.com',
    iosClientId: '640794025510-lcqm3a2anhum7e5c03osg32n7vh8q80p.apps.googleusercontent.com',
    iosBundleId: 'com.example.leoAnime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCas0a9mEHAQok97n-mGC3uY6ysQqESHRs',
    appId: '1:640794025510:ios:b0cb88d99e23efd05190e7',
    messagingSenderId: '640794025510',
    projectId: 'leo-anime-auth',
    storageBucket: 'leo-anime-auth.appspot.com',
    iosClientId: '640794025510-lcqm3a2anhum7e5c03osg32n7vh8q80p.apps.googleusercontent.com',
    iosBundleId: 'com.example.leoAnime',
  );
}
